### ISSUE TITLE
Song Request

### ISSUE THREAD

**Issue by quanduongduc** [tan264/TuNeMusiK#29]
Hi @tan264,
This song has brought a deeply emotional response from me. Might you add it to your application?
 
 <div align="center">
<a href="https://open.spotify.com/track/2ZQ6YMcGxwyvAfV6dl8hkB?si=9bd674057de14777" target="_blank">
    <img src="https://github.com/tan264/TuNeMusiK/assets/59951771/b648002e-b224-40c2-b634-14889a220e76" alt="Spotify track" style="border-radius:12px; width:100%; max-width:300px; height:auto;">
</a>

</div>
                                                    

>                                          "There's no truth I hide from you
>                                            Know I've never lied to you
>                                            When I said that I need you"

**Comment by tan264** [comment]
Hi Dảkwuan,
Thank you very much for your request. But I am sorry to inform you that I will close this project.
True to the mission of the project, the first goal was completed, but I realize that the second goal is too difficult to achieve. Therefore, closing it is currently the best way for me to get rid of everything related to that part of my priceless memories. 
I really appreciate your donation of EC2 resources.

A bouquet for you, the EC2 sponsor!
![c2fa28bc91d743c20006d9b85b55f744d0091ea0](https://github.com/tan264/TuNeMusiK/assets/87571262/c88a4bdb-5606-4e8e-800d-e7a5dea91e6a)
